repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-json
    -   id: mixed-line-ending
    -   id: check-merge-conflict
    -   id: debug-statements
-   repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        language_version: python3
        args: ["-l", "120", "--target-version", "py311"]
-   repo: https://github.com/PyCQA/flake8
    rev: 7.1.0
    hooks:
    - id: flake8
      exclude: ^figures/
